### ISSUE TITLE
btn_read() poweroff being called every y of the smiley drawing code

### ISSUE THREAD

**Issue by Querijn** [rajkosto/biskeydump#2]
Hey there, looking through your code to use it as a base for my own stuff, but it seems that the button check is done every Y step of the smiley.. 

Not sure how terribly it affects performance seeing as you're drawing a shadertoy on the CPU but I as wondering if this was done with intent or just simply a bug 😄

**Comment by rajkosto** [comment]
Intentional, so you dont have to wait until the smiley is drawn when you press the button for the button to actually react.
