### ISSUE TITLE
Show multiple small QR codes instead of a big one

### ISSUE THREAD

**Issue by DarthJahus** [rajkosto/biskeydump#3]
Using a huge QR code to agglomerate all the keys make it impossible to read by low resolution cameras. I was using a Moto G5 Plus (XT1680) and couldn't scan any of them; had to write them down manually. Of course, this is not a complaint. However, I think that it would be nicer to show multiple QR codes, one for each key; with less redondance needed in the QRs, they should be clearer even for PC cameras.

**Comment by rajkosto** [comment]
read the keys out by using TegraRcmSmash usb readback mode as the readme mentions, or just save them to microsd card and read that out.
