### ISSUE TITLE
v7 Doesn't dump all keys to file.

### ISSUE THREAD

**Issue by ccfman2004** [rajkosto/biskeydump#5]
Being able for the app to write the keys to a text file is very convenient but it doesn't print all keys.  None of the (tweak) keys are in the text file it generates.

**Comment by rajkosto** [comment]
Yes they are. It dumps in hactoolnet format in which crypt and tweak are concatenated together.

**Comment by ccfman2004** [comment]
It's useless as you need them separated for HacDiskMount as it asks for them separated.
EDIT:  Now I see there are the same line as a 32 byte block instead of 2 16 byte blocks.  Never mind .
