### ISSUE TITLE
8.1.0 TSEC FW differences

### ISSUE THREAD

**Issue by yuiyamu** [rajkosto/biskeydump#7]
8.1.0 seems to have a different TSEC FW, I tried with my switch and it worked fine in 8.0.1 but when I updated to 8.1.0 it spits out an error getting TSEC key.

**Comment by rajkosto** [comment]
Fixed in https://github.com/rajkosto/biskeydump/commit/ed57dd5032840ab7084bcd76e8b9408dd7245958
